[platformio]
src_dir = src
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = +<firmware/>

[env:esp32cam]
platform = espressif32@7.0.1
board = esp32cam
framework = arduino
monitor_speed = 115200
build_src_filter = +<espcam/>
