[project]
name = "gestos"
version = "0.1.0"
description = "Código identificador de gestos feito para o rewrite do treinee 2026/01 da ERUS"
readme = "README.md"
authors = [
    { name = "Dimitry Deveza", email = "dimydeveza@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cv2-enumerate-cameras>=1.3.2",
    "mediapipe>=1.0.1",
    "opencv-python-headless>=5.0.0.93",
    "pyside6>=6.10",
]

[project.scripts]
gestos = "gestos:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
